//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errors
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Patronomyc { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Urgently { get; set; }
    }
}
